// Package tripadvice wraps the operator-configured AI provider to
// generate plain-language observations about a Rivian trip plan:
// charging stop summary, arrival SoC commentary, adapter warnings,
// and drive-mode suggestions when the plan looks sub-optimal.
//
// Structure mirrors internal/recap: side-effect-free buildPrompt,
// stateless Generate, structured JSON output the SPA renders as a
// card below the route table.
package tripadvice

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/apohor/rivolt/internal/ai"
	"github.com/apohor/rivolt/internal/rivian"
)

// Context bundles user-supplied labels and request parameters that
// would otherwise be unavailable in the plan response itself.
type Context struct {
	OriginLabel      string
	DestinationLabel string
	// DriveMode is the mode the user explicitly chose, or "" for
	// "let the planner pick". Included so the model can say "you
	// planned in Conserve mode" rather than treating it as a mystery.
	DriveMode    string
	StartingSoC  float64
	HasAdapter   bool
}

// Result is what Generate returns to the handler.
type Result struct {
	// Raw is the model's reply, stored and forwarded as-is.
	Raw          string
	Parsed       *Parsed
	Model        string
	InputTokens  int64
	OutputTokens int64
}

// Parsed is the structured JSON shape the model emits.
type Parsed struct {
	Headline string   `json:"headline"`
	Insights []string `json:"insights"`
}

// Generate calls the AI provider with a compact trip-plan summary
// and returns structured advice. The context's deadline should be
// generous (30s+) — sit in the AI-bound route group, not the timed
// one.
func Generate(ctx context.Context, a *ai.Analyzer, plan *rivian.TripPlan, tc Context) (Result, error) {
	system, user := buildPrompt(plan, tc)
	raw, usage, err := a.Complete(ctx, system, user)
	if err != nil {
		return Result{}, err
	}
	var res Result
	res.Raw = raw
	res.Model = a.ModelName()
	res.InputTokens = usage.InputTokens
	res.OutputTokens = usage.OutputTokens
	res.Parsed = parse(raw)
	return res, nil
}

func parse(s string) *Parsed {
	s = strings.TrimSpace(s)
	// Strip optional markdown code fence.
	if after, ok := strings.CutPrefix(s, "```json"); ok {
		s = strings.TrimSuffix(strings.TrimSpace(after), "```")
	} else if after, ok := strings.CutPrefix(s, "```"); ok {
		s = strings.TrimSuffix(strings.TrimSpace(after), "```")
	}
	var p Parsed
	if err := json.Unmarshal([]byte(s), &p); err != nil {
		return nil
	}
	return &p
}

func buildPrompt(plan *rivian.TripPlan, tc Context) (system, user string) {
	const sys = `You are a concise Rivian trip-planning assistant. ` +
		`You receive a summary of a trip plan generated by Rivian's own planner and the user's starting parameters. ` +
		`Return a single JSON object — nothing before or after it — with this exact shape:
` +
		"```\n" +
		`{"headline":"<8 words or fewer>","insights":["<sentence>","<sentence>"]}` + "\n```\n" +
		`Rules:
- 2 to 4 insights, each one concrete and specific to the numbers below.
- Lead with the most actionable observation (tight arrival SoC, long charge stop, adapter dependency).
- If drive mode was left at default and a different mode would clearly help (e.g. Conserve saves >15 min on a long trip), say so.
- Do not invent numbers not present in the plan summary.
- No emoji, no marketing language, no filler.`

	var sb strings.Builder
	fmt.Fprintf(&sb, "Origin: %s\n", labelOrUnknown(tc.OriginLabel))
	fmt.Fprintf(&sb, "Destination: %s\n", labelOrUnknown(tc.DestinationLabel))
	fmt.Fprintf(&sb, "Starting SoC: %.0f%%\n", tc.StartingSoC)
	if tc.DriveMode != "" {
		fmt.Fprintf(&sb, "Drive mode: %s\n", tc.DriveMode)
	} else {
		fmt.Fprintf(&sb, "Drive mode: default (planner chose)\n")
	}
	if tc.HasAdapter {
		fmt.Fprintf(&sb, "Tesla NACS adapter: yes\n")
	}
	fmt.Fprintln(&sb)

	if len(plan.Routes) == 0 {
		fmt.Fprintf(&sb, "The planner returned no viable routes. Status: %s\n", plan.Status)
		if plan.SoCBelowLimit {
			fmt.Fprintln(&sb, "Rivian flagged SoC as below the configured limit.")
		}
		if !plan.ChargeStationsAvailable {
			fmt.Fprintln(&sb, "No charge stations available along the corridor.")
		}
		return sys, sb.String()
	}

	for i, r := range plan.Routes {
		charging := chargeStops(r)
		totalChargeMin := r.TotalChargingDurationSec / 60
		fmt.Fprintf(&sb, "Route %d:\n", i+1)
		fmt.Fprintf(&sb, "  Destination reached: %v\n", r.DestinationReached)
		fmt.Fprintf(&sb, "  Charging stops: %d\n", len(charging))
		if totalChargeMin > 0 {
			fmt.Fprintf(&sb, "  Total charge time: %d min\n", totalChargeMin)
		}
		if r.ArrivalSoC > 0 {
			fmt.Fprintf(&sb, "  Arrival SoC: %.0f%%\n", r.ArrivalSoC)
		}
		if r.EnergyConsumptionKWh > 0 {
			fmt.Fprintf(&sb, "  Energy used: %.1f kWh\n", r.EnergyConsumptionKWh)
		}
		if !r.DestinationReached && r.BatteryEmptyToDestMeters > 0 {
			fmt.Fprintf(&sb, "  Battery empty %.0f km short of destination\n", r.BatteryEmptyToDestMeters/1000)
		}
		for j, w := range charging {
			fmt.Fprintf(&sb, "  Stop %d: %s\n", j+1, stopLabel(w))
			fmt.Fprintf(&sb, "    Arrive %.0f%% → depart %.0f%% (%d min", w.ArrivalSoC, w.DepartureSoC, w.ChargeDurationSec/60)
			if w.MaxPowerKW > 0 {
				fmt.Fprintf(&sb, ", max %.0f kW", w.MaxPowerKW)
			}
			fmt.Fprintln(&sb, ")")
			if w.AdapterRequired {
				fmt.Fprintln(&sb, "    Adapter required at this stop.")
			}
		}
		if plan.SoCBelowLimit {
			fmt.Fprintln(&sb, "  Rivian flagged SoC below limit.")
		}
	}
	return sys, sb.String()
}

func chargeStops(r rivian.TripRoute) []rivian.PlannedWaypoint {
	var out []rivian.PlannedWaypoint
	for _, w := range r.Waypoints {
		t := strings.ToUpper(w.WaypointType)
		if t != "ORIGIN" && t != "DESTINATION" && t != "OTHER" {
			out = append(out, w)
		}
	}
	return out
}

func stopLabel(w rivian.PlannedWaypoint) string {
	if w.Name != "" {
		return w.Name
	}
	return fmt.Sprintf("(%.3f, %.3f)", w.Latitude, w.Longitude)
}

func labelOrUnknown(s string) string {
	if s == "" {
		return "unknown"
	}
	return s
}
