// Package invites manages single-use invite codes for beta sign-up.
//
// Codes are 20-character URL-safe random strings generated by the
// admin. Each code may be redeemed exactly once; Redeem uses an
// UPDATE...WHERE used_at IS NULL so concurrent redemption attempts
// leave only one winner.
package invites

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base32"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// ErrInvalidCode is returned when a code does not exist or has
// already been redeemed.
var ErrInvalidCode = errors.New("invite code invalid or already used")

// Code is the public view of an invite_codes row.
type Code struct {
	Code      string
	CreatedAt time.Time
	UsedAt    *time.Time
	UsedBy    *string // email of the user who redeemed it, nil if unused
}

// Store wraps the invite_codes table.
type Store struct {
	db *sql.DB
}

// New returns a Store backed by db.
func New(db *sql.DB) *Store { return &Store{db: db} }

// Generate creates count single-use invite codes owned by createdBy
// and returns the plaintext code strings.
func (s *Store) Generate(ctx context.Context, createdBy uuid.UUID, count int) ([]string, error) {
	if count < 1 || count > 100 {
		return nil, fmt.Errorf("invites: count must be 1–100, got %d", count)
	}
	codes := make([]string, count)
	for i := range codes {
		c, err := randomCode()
		if err != nil {
			return nil, fmt.Errorf("invites: generate code: %w", err)
		}
		codes[i] = c
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback() //nolint:errcheck
	for _, c := range codes {
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO invite_codes (code, created_by) VALUES ($1, $2)`,
			c, createdBy,
		); err != nil {
			return nil, fmt.Errorf("invites: insert code: %w", err)
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return codes, nil
}

// Validate checks that code exists and has not been redeemed.
// Returns ErrInvalidCode when it does not exist or is already used.
func (s *Store) Validate(ctx context.Context, code string) error {
	code = strings.TrimSpace(code)
	if code == "" {
		return ErrInvalidCode
	}
	var usedAt sql.NullTime
	err := s.db.QueryRowContext(ctx,
		`SELECT used_at FROM invite_codes WHERE code = $1`, code,
	).Scan(&usedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return ErrInvalidCode
	}
	if err != nil {
		return fmt.Errorf("invites: validate: %w", err)
	}
	if usedAt.Valid {
		return ErrInvalidCode
	}
	return nil
}

// Redeem atomically marks code as used by userID. Returns
// ErrInvalidCode when the code was already redeemed or does not exist.
func (s *Store) Redeem(ctx context.Context, code string, userID uuid.UUID) error {
	res, err := s.db.ExecContext(ctx,
		`UPDATE invite_codes
		    SET used_by = $1, used_at = NOW()
		  WHERE code = $2 AND used_at IS NULL`,
		userID, code,
	)
	if err != nil {
		return fmt.Errorf("invites: redeem: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrInvalidCode
	}
	return nil
}

// List returns all invite codes, most-recently-created first.
// usedBy is the email of the redeeming user when known.
func (s *Store) List(ctx context.Context) ([]Code, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT ic.code, ic.created_at, ic.used_at, u.email
		  FROM invite_codes ic
		  LEFT JOIN users u ON u.id = ic.used_by
		 ORDER BY ic.created_at DESC
	`)
	if err != nil {
		return nil, fmt.Errorf("invites: list: %w", err)
	}
	defer rows.Close()
	out := make([]Code, 0)
	for rows.Next() {
		var c Code
		var usedAt sql.NullTime
		var email sql.NullString
		if err := rows.Scan(&c.Code, &c.CreatedAt, &usedAt, &email); err != nil {
			return nil, err
		}
		if usedAt.Valid {
			t := usedAt.Time
			c.UsedAt = &t
		}
		if email.Valid {
			s := email.String
			c.UsedBy = &s
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// randomCode returns a 20-char URL-safe base32 string (100 bits of
// randomness). Dashes and lowercase make codes easier to read/type.
func randomCode() (string, error) {
	b := make([]byte, 13) // ceil(20 * 5 / 8) = 13 bytes → 20 base32 chars
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return strings.ToUpper(base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(b))[:20], nil
}
