-- 0007_vehicle_state_partition.sql
--
-- Convert `vehicle_state` from a single heap to a RANGE-partitioned
-- table by month on `at`. Closes Phase-1 roadmap item "samples
-- partitioned by month from day one".
--
-- # Why partitioning, why now
--
-- `vehicle_state` is the one genuine growth table in Rivolt — the
-- live recorder writes ~1 row / 30s per vehicle, so at 1000 vehicles
-- we're looking at ~2.9M rows/month, ~35M rows/year. A single heap
-- works fine at the homelab scale we're at today, but retrofitting
-- partitioning under a live table requires either a CONCURRENTLY
-- dance or a maintenance window — neither of which we want to buy
-- on our way to 1000 vehicles. Landing the partitioning now, while
-- the table is still small, means:
--
--   - DROP-by-partition reclaims space instantly (no VACUUM FULL),
--     so a retention policy becomes trivial later.
--   - Query planner prunes to the month(s) of interest for any
--     `WHERE at > $since` filter — which is every read path.
--   - TimescaleDB / pg_partman drop-in at phase 3 is a rewrite
--     of one migration + one janitor, not of every read query.
--
-- # Why hand-rolled, not pg_partman
--
-- pg_partman is great but adds a cluster-level extension dependency
-- that self-hosters have to install. We need exactly one thing from
-- it — "create next month's partition on a schedule" — and a 20-line
-- PL/pgSQL function + a Go boot-time call cover it. Phase 3 can
-- graduate to pg_partman if we ever want its retention automation.

-- Disable any cluster-default statement_timeout for the duration of
-- this migration's tx. The boot context already enforces a generous
-- ceiling on db.Open; we don't want a 30s default in postgresql.conf
-- or in PGOPTIONS to bite the data copy on a populated heap. SET
-- LOCAL is tx-scoped and reverts on COMMIT/ROLLBACK.
SET LOCAL statement_timeout = 0;
SET LOCAL lock_timeout      = 0;

-- -------------------------------------------------------------------
-- 1. New partitioned parent, same shape as the existing heap. All
--    indexes declared here become partitioned indexes (PG11+), which
--    means every partition automatically inherits them.
-- -------------------------------------------------------------------
CREATE TABLE vehicle_state_new (
    vehicle_id        UUID NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    at                TIMESTAMPTZ NOT NULL,
    user_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    battery_level_pct DOUBLE PRECISION,
    range_mi          DOUBLE PRECISION,
    odometer_mi       DOUBLE PRECISION,
    lat               DOUBLE PRECISION,
    lon               DOUBLE PRECISION,
    speed_mph         DOUBLE PRECISION,
    shift_state       TEXT,
    charging_state    TEXT,
    charger_power_kw  DOUBLE PRECISION,
    charge_limit_pct  DOUBLE PRECISION,
    inside_temp_c     DOUBLE PRECISION,
    outside_temp_c    DOUBLE PRECISION,
    drive_number      BIGINT,
    charge_number     BIGINT,
    source            TEXT NOT NULL,
    raw               JSONB,
    -- PK must include the partition key — that's fine, (vehicle_id, at)
    -- was already the natural dedupe key for both the live recorder
    -- and the ElectraFi importer.
    PRIMARY KEY (vehicle_id, at)
) PARTITION BY RANGE (at);

CREATE INDEX vehicle_state_new_user_at ON vehicle_state_new (user_id, at DESC);

-- -------------------------------------------------------------------
-- 2. Create every monthly partition covering the existing heap's
--    data range plus 6 months into the future so the live recorder
--    has room to write. The janitor keeps this window rolling.
-- -------------------------------------------------------------------
DO $$
DECLARE
    earliest TIMESTAMPTZ;
    latest   TIMESTAMPTZ;
    cur      TIMESTAMPTZ;
    nm       TEXT;
BEGIN
    SELECT
        COALESCE(date_trunc('month', MIN(at)), date_trunc('month', NOW() - INTERVAL '1 month')),
        date_trunc('month', NOW()) + INTERVAL '6 months'
    INTO earliest, latest
    FROM vehicle_state;

    cur := earliest;
    WHILE cur < latest LOOP
        nm := 'vehicle_state_y' || to_char(cur AT TIME ZONE 'UTC', 'YYYY_MM');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF vehicle_state_new FOR VALUES FROM (%L) TO (%L)',
            nm, cur, cur + INTERVAL '1 month'
        );
        cur := cur + INTERVAL '1 month';
    END LOOP;
END $$;

-- -------------------------------------------------------------------
-- 3. Copy. The INSERT … SELECT routes each row to its month's
--    partition automatically. For self-host installs this is < 1M
--    rows and completes in seconds inside the migration tx.
-- -------------------------------------------------------------------
INSERT INTO vehicle_state_new
SELECT * FROM vehicle_state;

-- -------------------------------------------------------------------
-- 4. Swap. DROP old heap, rename the parent into place, and tidy
--    the autogenerated names so a future operator seeing `\d
--    vehicle_state` in psql doesn't find surprise `_new_` prefixes.
-- -------------------------------------------------------------------
DROP TABLE vehicle_state;
ALTER TABLE vehicle_state_new RENAME TO vehicle_state;
ALTER INDEX vehicle_state_new_user_at RENAME TO vehicle_state_user_at;
ALTER TABLE vehicle_state RENAME CONSTRAINT vehicle_state_new_pkey TO vehicle_state_pkey;

-- -------------------------------------------------------------------
-- 5. Install the partition-maintenance helper. The Go janitor calls
--    this at boot + hourly for (now, now + N months) so the live
--    recorder never writes into an unpartitioned range.
--
-- Idempotent by design — `to_regclass` returns NULL when the child
-- table doesn't exist yet, and CREATE TABLE IF NOT EXISTS is belt
-- over that suspenders. Naming scheme vehicle_state_yYYYY_MM is
-- chosen to sort lexically by month, which makes `\dt vehicle_state_y*`
-- output chronological without explicit ORDER BY.
-- -------------------------------------------------------------------
CREATE OR REPLACE FUNCTION rivolt_ensure_vehicle_state_partition(when_ts TIMESTAMPTZ)
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
    month_start TIMESTAMPTZ := date_trunc('month', when_ts);
    month_end   TIMESTAMPTZ := month_start + INTERVAL '1 month';
    part_name   TEXT        := 'vehicle_state_y' || to_char(month_start AT TIME ZONE 'UTC', 'YYYY_MM');
BEGIN
    IF to_regclass(part_name) IS NULL THEN
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF vehicle_state FOR VALUES FROM (%L) TO (%L)',
            part_name, month_start, month_end
        );
    END IF;
    RETURN part_name;
END;
$$;
